# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=20)),
                ('photography_type', models.CharField(choices=[('co', 'color'), ('bl', 'black and white'), ('la', 'landscape'), ('st', 'still life'), ('co', 'commercial'), ('ad', 'advertising'), ('fo', 'food'), ('ph', 'photojournalism'), ('po', 'portrait and wedding'), ('wi', 'wildlife'), ('am', 'amateur'), ('cr', 'crime scene'), ('fa', 'fashion'), ('ed', 'editorial')], default='amateur', max_length=2)),
                ('region', models.CharField(choices=[('Af', 'Africa'), ('Eu', 'Europe'), ('As', 'Asia'), ('No', 'North America'), ('So', 'South America'), ('An', 'Antarctica'), ('Au', 'Australia')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
