# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_remove_imagerprofile_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(default='', max_length=20),
        ),
    ]
